### ISSUE TITLE
using aur-auto-vote on multiple systems with the same account

### ISSUE THREAD

**Issue by 0-st** [cryzed/bin#2]
Using your script to update votes on multiple systems that don't have the same packages installed doesn't work, is there a solution to this? 

I could save a list on each system with the installed packages, merge them and use it with the ignore flag but as I understand correctly this only prevents packages from being voted on and not from being unvoted? Or is there a workaround that I'm missing?

I don't know if it's possible to use something similar to pacserve to check installed packages between different systems on the same network?

Thanks anyway, it already saved me lots of time not having to manually unvote the completely outdated voted-for packages.

**Comment by cryzed** [comment]
Sorry for the late answer, but this seems outside the scope that I had planned for the script for now. I admittedly hadn't considered multi-system setups, since I only run the script on my main installation. However when I start considering which flags and switches to add to the script to work around this problem, it seems to get quite complex very quickly -- so I'm not sure what to do exactly.
