### ISSUE TITLE
hotkeys?

### ISSUE THREAD

**Issue by dufferzafar** [cryzed/bin#5]
Hi! hotstrings is amazing!

Do you know if there is a Xlib based hotkeys script too?

**Comment by cryzed** [comment]
There's there [Python 3 Autokey fork](https://github.com/autokey-py3/autokey) which seems to be maintained. If I'm not mistaken, it should support hotkeys and even the things you asked in #6. Consider this the response to both of your issues.

PS: As a friendly heads-up: if you plan to include other people's MIT-licensed software into your own projects in the future, for example like you did [here](https://github.com/dufferzafar/chotu/blob/99694ba3823c80f1f5dbf7ac55388290f09bd575/lib_hotstrings.py), you should followed the MIT license guidelines, as described [here](https://github.com/cryzed/bin/blob/master/LICENSE), especially this part:

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

Although I think this point will be moot soon, since you'll probably start using Autokey, what you did [here](https://github.com/dufferzafar/chotu/blob/99694ba3823c80f1f5dbf7ac55388290f09bd575/lib_hotstrings.py#L1-L6) is not actually in lines with the requirements of the license: your modifications (mostly removal of unrelated code) still substitues a "substantial portion of the Software".
